// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace br.com.multi_schema.poc
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class TopicDataTypeOne : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TopicDataTypeOne\",\"namespace\":\"br.com.multi_schema.poc\"," +
				"\"fields\":[{\"name\":\"id\",\"type\":\"bytes\"},{\"name\":\"data_type\",\"type\":\"string\"}]}");
		private byte[] _id;
		private string _data_type;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return TopicDataTypeOne._SCHEMA;
			}
		}
		public byte[] id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string data_type
		{
			get
			{
				return this._data_type;
			}
			set
			{
				this._data_type = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.data_type;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Byte[])fieldValue; break;
			case 1: this.data_type = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
